### ISSUE TITLE
Adjust the concept of serialization

### ISSUE THREAD

**Issue by felipemmelo** [AbsaOSS/py2k#34]
In the readme, the example currently available is like below.

```py
from py2k.models import DynamicKafkaModel
from py2k.writer import KafkaWriter

# assuming we have a pandas DataFrame, df
serialized_df = DynamicKafkaModel(df=df,model_name='test_model').from_pandas()

writer = KafkaWriter(
    topic="topic_name",
    schema_registry_config=schema_registry_config,
    producer_config=producer_config
)

writer.write(serialized_df)
```

This library is about Avro, and in Avro parlance, serialization refers to formatting data as Avro. 

In the example above, `serialized_df` is not in Avro format, so calling it `serialized` is misleading. 

Also, it might be worth to change names across the whole library to refer to `serialization` only when it is about converting data to Avro, in order to avoid confusing users and contributors.

**Comment by vesely-david** [comment]
Adding relevant renaming points from today's discussion, 

- model_name -> recored_obj_name in DynamicKafkaModel to hide the Pydantic naming
- serialzed_df -> records adhering to Kafka parlance
- item -> record (same as above)
