### ISSUE TITLE
Posibility to specify whether key will be included in value

### ISSUE THREAD

**Issue by vesely-david** [AbsaOSS/py2k#40]
The current implementation includes key data into value without the possibility to choose whether it is necessary.

We propose to add a boolean flag "include_key" to KafkaWriter to enable choosing whether the user wants to have key data included in the value.

The default behavior should be false

**Comment by DanWertheimer** [comment]
Should this not be included in `KafkaModel` not `KafkaWriter`? If we're moving the key generation into there.

**Comment by vesely-david** [comment]
100 %, this was "typo"
